import Addresses from '@/components/addresses/Addresses'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
import Code from '@/components/code/Code'
import { ToggleContext } from '@/context/toggleContext/ToggleContext'
import Color_Context from '@/context/colorcontext/Color_Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className='container'>
          <Header />
          <ToggleContext>
            <Color_Context>
              <div className='content' >
                <Addresses />
                <div className='children'>
                  {children}
                  <Code />
                </div>
              </div>
            </Color_Context>
          </ToggleContext>
          <Footer />
        </div>
      </body>
    </html>
  )
}
